### ISSUE TITLE
не грузятся картинки с auto.ru

### ISSUE THREAD

**Issue by fisheract** [devmanorg/tesla-spider#1]
Здравствуйте просмотрел ваш туториал по парсингу сайтов и возник вопрос. Почему в данный момент не работает код

tesla-spider/auto_ru.py 
20 строка
img_urls = car_div.css('.Brazzers__image::attr(data-src)').getall()

**Comment by pelid** [comment]
На сайте изменилась вёрстка. Можно перейти по ссылке [https://auto.ru/balashiha/cars/tesla/all/?currency=EUR](https://auto.ru/balashiha/cars/tesla/all/?currency=EUR) и открыть Chrome Dev Tools, вкладку Elements. Если теперь поискать селектор `.ListingCars-module__listingItem`, то такого на странице не окажется.

![image](https://user-images.githubusercontent.com/870324/90357806-dc8c0b80-e05c-11ea-991c-3e79adbd6c7e.png)

[_auto_ru.py:10_](https://github.com/devmanorg/tesla-spider/blob/66b43289890f3b3e043505603694fce4e2a4cfda/auto_ru.py#L10-L11)
```
def parse(self, response):
    for car_div in response.css('.ListingCars-module__listingItem'):
```

Надо обновить все селекторы в коде.

**Comment by fisheract** [comment]
Благодарю за ответ
